name: MiBingo
version: ${project.version}
main: com.bingaso.bingo.BingoPlugin
api-version: "1.21.8"
description: Plugin de bingo
author: Sergio
api: 1.21.8

commands:
  bingo:
    description: Bingo management
    usage: |
      /bingo <create|team|start|config|card>
      Use '/bingo' for help with subcommands.
    aliases: [bg]
