name: MiBingo
version: ${project.version}
main: com.bingaso.bingo.BingoPlugin
api-version: "1.21.8"
description: Plugin de bingo
author: Sergio
api: 1.21.8

commands:
  bingoteam:
    description: Team management commands
    usage: /bingoteam <create|join|leave|list|info|select>
    aliases: [bt, bingoteams]
  bingostart:
    description: Bingo Start command
    usage: /bingostart
    aliases: [bs]
  bingocard:
    description: Bingo Card command
    usage: /bingocard
    aliases: [bc]
  bingoconfig:
    description: Bingo Configuration command
    usage: /bingoconfig
    aliases: [bg]
