name: MiBingo
version: ${project.version}
main: com.bingaso.bingo.BingoPlugin
api-version: "1.21.8"
description: Plugin de bingo
author: Sergio
api: 1.21.8

commands:
  team:
    description: Team management commands
    usage: /team <create|join|leave|list|info>
    aliases: [t, teams]
